---
sudo: required
language: python3
services: docker

before_install:
  - sudo apt update
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367

addons:
  apt:
    update: true

env:
  - version=">=2.7,<2.8" distro="centos-latest"

matrix:
  allow_failures:
    - env: version="devel" distro="centos-latest"

cache:
  - pip

install:
  - sudo apt update
  - sudo apt upgrade -y
  - sudo apt install -y ansible
  - sudo apt install -y python3 python3-pip
  - sudo python3 -m pip install --user molecule
  - sudo python3 -m pip install --user molecule[docker]
  - sudo python3 -m pip install --user docker

script:
  - molecule test --scenario-name "${distro}"
